apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-ingress  
spec:  
  rules:
  - host: microservices.info
    http:
      paths:
      - path: /employee
        backend:
          serviceName: employee
          servicePort: 8080
      